# Generated by Django 5.2.9 on 2026-03-06 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0002_userotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userNotifications',
            fields=[
                ('statusUpdatesId', models.AutoField(primary_key=True, serialize=False)),
                ('status_content', models.TextField(max_length=256)),
                ('status_update_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
