# Generated by Django 5.2.9 on 2026-03-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0003_usernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='context',
            field=models.CharField(default='public_use', max_length=50),
        ),
        migrations.AddField(
            model_name='identity',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('contextually_restricted', 'contextually_restricted'), ('Specific_Client', 'Specific_Client')], default='public', max_length=50),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('accessible_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identityApiApp.identity')),
            ],
        ),
    ]
