# Generated by Django 5.2.9 on 2026-03-09 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0004_identity_context_identity_visibility_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='identity',
            name='context',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='identity_type',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usernotifications',
            name='statusUpdatesId',
        ),
        migrations.AddField(
            model_name='identity',
            name='security_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='identity',
            name='identity_context',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='identityApiApp.context'),
        ),
    ]
