# Generated by Django 5.2.9 on 2026-03-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0005_context_remove_identity_context_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotifications',
            old_name='status_content',
            new_name='notification_content',
        ),
        migrations.RenameField(
            model_name='usernotifications',
            old_name='status_update_date',
            new_name='notification_update_date',
        ),
    ]
