# Generated by Django 5.2.9 on 2026-03-12 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0007_identity_linked_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='linked_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identity',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('contextually_restricted', 'Only for the selected Context'), ('Specific_Client', 'Only for Specific Client sites')], default='public', max_length=50),
        ),
    ]
