# Generated by Django 5.2.9 on 2026-03-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0008_context_linked_user_alter_identity_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='accessible_identity',
        ),
        migrations.AddField(
            model_name='identity',
            name='linked_platforms',
            field=models.ManyToManyField(blank=True, to='identityApiApp.platform'),
        ),
    ]
