# Generated by Django 5.2.9 on 2026-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0009_remove_platform_accessible_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('contextually_restricted', 'Only for the selected Context'), ('specific_client', 'Only for Specific Client sites')], default='public', max_length=50),
        ),
    ]
