# Generated by Django 5.2.9 on 2026-03-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0010_alter_identity_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotifications',
            old_name='notification_update_date',
            new_name='created_date',
        ),
    ]
