# Generated by Django 5.2.9 on 2026-03-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0013_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='linked_platforms',
        ),
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=128, unique=True)),
                ('accessible_contexts', models.ManyToManyField(blank=True, to='identityApiApp.context')),
            ],
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
