# Generated by Django 5.2.9 on 2026-03-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0014_remove_identity_linked_platforms_apiclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='priority_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_for_contexts', to='identityApiApp.identity'),
        ),
    ]
