# Generated by Django 5.2.9 on 2026-03-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0015_context_priority_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='security_level',
            field=models.CharField(choices=[('low', 'Low: Just notifications from the site when your identity is being requested for'), ('medium', 'Medium: Site and email notifications when your identity is being requested for'), ('high', 'High: An OTP will be required before this identity is retrieved')], default='low', max_length=10),
        ),
    ]
