# Generated by Django 5.2.9 on 2026-03-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0016_alter_identity_security_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='related_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
