# Generated by Django 5.2.9 on 2026-03-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0017_identity_related_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiclient',
            name='accessible_contexts',
        ),
        migrations.AddField(
            model_name='apiclient',
            name='priority_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_for_client', to='identityApiApp.identity'),
        ),
    ]
