# Generated by Django 5.2.9 on 2026-03-16 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0019_rename_name_apiclient_client_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apiclient',
            constraint=models.UniqueConstraint(fields=('linked_user', 'client_name'), name='unique_client_per_user'),
        ),
    ]
