# Generated by Django 5.2.9 on 2026-03-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0020_apiclient_unique_client_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='related_info',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
