# Generated by Django 5.2.9 on 2026-03-18 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0021_alter_identity_related_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='verified_users',
            field=models.ManyToManyField(blank=True, related_name='verified_api_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='linked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_api_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identity',
            name='security_level',
            field=models.CharField(choices=[('low', 'Low: You will receieve notifications from the site whenever your identity is being requested for'), ('medium', 'Medium: You will receive site notifications and need to enter an OTP for first time said identity is requested and thats all.'), ('high', 'High: An OTP will be required everytime this identity is retrieved')], default='low', max_length=10),
        ),
    ]
