# Generated by Django 5.2.9 on 2026-03-18 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0022_apiclient_verified_users_alter_apiclient_linked_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='verified_users',
            field=models.ManyToManyField(blank=True, related_name='verified_context_api_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='context',
            name='linked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_context_api_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
