# Generated by Django 5.2.9 on 2026-03-20 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityApiApp', '0023_context_verified_users_alter_context_linked_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='context_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='context',
            constraint=models.UniqueConstraint(fields=('linked_user', 'context_name'), name='unique_context_per_user'),
        ),
    ]
